### ISSUE TITLE
Plugin static resources can't be loaded.

### ISSUE THREAD

**Issue by nicroto** [loanlaux/reaction-hydrotik-plugin#2]
Just tried installing the theme plugin, but I don't see the custom data (no added products), nor the images get loaded.

<img width="1440" alt="screen shot 2018-05-01 at 7 00 20 pm" src="https://user-images.githubusercontent.com/1172150/39480799-006183a8-4d72-11e8-95e3-e2ca0fa3aad9.png">

What I did was:

```shell
$ reaction init test-app && cd test-app
$ reaction pull
$ reaction update
$ reaction reset -n
$ git clone https://github.com/loanlaux/reaction-hydrotik-plugin imports/plugins/custom/reaction-hydrotik-plugin
$ reaction
```

I think there are setup steps missing from the README? Or maybe I am missing something about plugins in Reaction in general?

**Comment by loanlaux** [comment]
Fixed! Thanks a lot. 👍
